version: 1.0.0.{build}
configuration:
  - Release
  - Win10 Release
platform: Any CPU
# Install Pester
install:
    - cinst -y pester
clone_folder: c:\projects\PSLProvider
build_script:
    - ps: |
        $buildConfig = 'Release'
        & msbuild 'c:\projects\PSLProvider\PackageSourceListProvider.csproj' /logger:'C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll' /P:Configuration=$buildConfig 
#after_build:
#- ps: >-
#    Get-ChildItem "C:\projects\psl\output\Release\bin" -Recurse | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName releasebits -Type Auto }

before_test:
- ps: >-
    & "c:\projects\PSLProvider\Test\psl.tests.ps1"
